---
abstract: 'templating system for marc records'
author:
  - 'Marc Chantreux <khatar@phear.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300029, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: marc-mir-template
requires:
  Modern::Perl: 0
  YAML: 0
version: 0.1
